# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jaeheung Surh
email: jaeheungsurh@gmail.com
description: Jaeheung Surh's Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaeheungs.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github:
  repository_url: https://github.com/jaeheungs?tab=repositories
  github_username:  jaeheungs
linkedin:
  url: https://www.linkedin.com/in/jaeheung-surh-0a007b24/
cv: assets/pdf/jhscv.pdf
gscholar: https://scholar.google.com/citations?user=UYaHNtQAAAAJ&hl=en&oi=ao
collections:
  pubs:
    output: true

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
future: true
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
